version: '3'
services:
  mysql:
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD: ${SQL_PW:-test}
    image: mariadb:latest
    volumes:
      - ${MYSQLDIR:-./data/mysql}:/docker-entrypoint-initdb.d/
      ##https://github.com/docker-library/mariadb/blob/master/10.5/docker-entrypoint.sh#L53

      psql:
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD: ${SQL_PW:-test}
    image: postgres:latest
    volumes:
      - ${PSQLDIR:-./data/psql}:/mnt/sql
##https://github.com/docker-library/postgres/blob/master/13/docker-entrypoint.sh#L147

  adminer: ## admin interface for postgresql
    image: adminer
    ports:
      - "${ADMINERPORT:-8080}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER: mysql
